version: '3.8'

services:
  agent_service:
    build: ./agent_service
    ports:
      - "8000:8000"
    environment:
      - AGENT_SERVICE_URL=http://agent_service:8000

  booking_service:
    build: ./booking_service
    ports:
      - "8001:8001"
    depends_on:
      - agent_service

  sales_service:
    build: ./sales_service
    ports:
      - "8002:8002"
    depends_on:
      - booking_service

  invoicing_service:
    build: ./invoicing_service
    ports:
      - "8003:8003"
    depends_on:
      - booking_service
